### ISSUE TITLE
the smallest tutorial that boots something interesting

### ISSUE THREAD

**Issue by josephholsten** [ns1/waitron#6]
The command in the README.md is interesting, but doesn't exactly yield a shiny demo. Could you perhaps give us a minimally interesting config file to use? Or a little more information about how to actually implement the bigger picture described?

**Comment by josephholsten** [comment]
btw, I'd absolutely love to just get on a chat or call with you and work out what's needed for this.

**Comment by jhaals** [comment]
Hi!
I'm no longer at the company where this where in use so It's not fresh in my mind. I've asked former colleague to possibly shed some light on the topic.

**Comment by jhaals** [comment]
@xnaveira ^

**Comment by Skarzee** [comment]
Would also love to see how this is done, as this could be a grand entry point to our infrastructure creation. Thanks!

**Comment by q2dg** [comment]
Well, it seems this project is pretty abandoned...what a pity

**Comment by hbokh** [comment]
@josephholsten Even though this project seems to be in need of some TLC, this might help you get started: https://hbokh.github.io/post/2018/12/01/pixiecore-waitron/
It's not going into `waitron` *in-depth*, but it's better than nothing I guess...

**Comment by bcavns01** [comment]
This is probably much more than too little too late, but we're trying to get something up based on the most recent changes to Waitron: https://github.com/ns1/waitron/tree/master/examples

I'm sure there's too much being implied in the very short list of steps in that how-to link, so for anyone still curious/interested who actually tries it out, let us know what blocks you and we'll expand the details in that how-to.
